'use strict';

const permissionCatalog = [
    { name: 'dashboard.view', module: 'dashboard', description: 'View dashboard' },
    { name: 'users.view', module: 'users', description: 'View users' },
    { name: 'users.create', module: 'users', description: 'Create users' },
    { name: 'users.update', module: 'users', description: 'Update users' },
    { name: 'users.delete', module: 'users', description: 'Delete users' },
    { name: 'roles.view', module: 'roles', description: 'View roles' },
    { name: 'roles.manage', module: 'roles', description: 'Create, update and delete roles' },
    { name: 'permissions.view', module: 'permissions', description: 'View permissions' },
    { name: 'permissions.manage', module: 'permissions', description: 'Manage permissions' },
    { name: 'products.view', module: 'products', description: 'View products' },
    { name: 'products.create', module: 'products', description: 'Create products' },
    { name: 'products.update', module: 'products', description: 'Update products' },
    { name: 'products.delete', module: 'products', description: 'Delete products' },
    { name: 'orders.view', module: 'orders', description: 'View orders' },
    { name: 'orders.create', module: 'orders', description: 'Create orders' },
    { name: 'orders.update', module: 'orders', description: 'Update orders' },
    { name: 'orders.cancel', module: 'orders', description: 'Cancel orders' },
    { name: 'orders.delete', module: 'orders', description: 'Delete orders and carts' },
    { name: 'customers.view', module: 'customers', description: 'View customers' },
    { name: 'customers.create', module: 'customers', description: 'Create customers' },
    { name: 'customers.update', module: 'customers', description: 'Update customers' },
    { name: 'customers.delete', module: 'customers', description: 'Delete customers' },
    { name: 'reports.view', module: 'reports', description: 'View reports' },
    { name: 'admin.dashboard.view', module: 'admin', description: 'View the administrative dashboard' },
    { name: 'inventory.view', module: 'inventory', description: 'View inventory' },
    { name: 'inventory.create', module: 'inventory', description: 'Create inventory records' },
    { name: 'inventory.update', module: 'inventory', description: 'Update inventory records' },
    { name: 'inventory.delete', module: 'inventory', description: 'Delete inventory records' },
    { name: 'deliveries.view', module: 'deliveries', description: 'View deliveries' },
    { name: 'deliveries.create', module: 'deliveries', description: 'Create deliveries' },
    { name: 'deliveries.update', module: 'deliveries', description: 'Update deliveries' },
    { name: 'deliveries.delete', module: 'deliveries', description: 'Delete deliveries' },
    { name: 'invoices.view', module: 'invoices', description: 'View invoices' },
    { name: 'invoices.create', module: 'invoices', description: 'Create invoices' },
    { name: 'invoices.update', module: 'invoices', description: 'Update invoices' },
    { name: 'invoices.delete', module: 'invoices', description: 'Delete invoices' },
    { name: 'item_images.view', module: 'item_images', description: 'View item images and videos' },
    { name: 'item_images.create', module: 'item_images', description: 'Create item images and videos' },
    { name: 'item_images.update', module: 'item_images', description: 'Update item images and videos' },
    { name: 'item_images.delete', module: 'item_images', description: 'Delete item images and videos' },
    { name: 'notification_preferences.view', module: 'notification_preferences', description: 'View notification preferences' },
    { name: 'notification_preferences.create', module: 'notification_preferences', description: 'Create notification preferences' },
    { name: 'notification_preferences.update', module: 'notification_preferences', description: 'Update notification preferences' },
    { name: 'notification_preferences.delete', module: 'notification_preferences', description: 'Delete notification preferences' },
    { name: 'notifications.view', module: 'notifications', description: 'View notifications' },
    { name: 'notifications.create', module: 'notifications', description: 'Create notifications' },
    { name: 'notifications.update', module: 'notifications', description: 'Update notifications' },
    { name: 'notifications.delete', module: 'notifications', description: 'Delete notifications' },
    { name: 'oauth_accounts.view', module: 'oauth_accounts', description: 'View OAuth accounts' },
    { name: 'oauth_accounts.create', module: 'oauth_accounts', description: 'Create OAuth accounts' },
    { name: 'oauth_accounts.update', module: 'oauth_accounts', description: 'Update OAuth accounts' },
    { name: 'oauth_accounts.delete', module: 'oauth_accounts', description: 'Delete OAuth accounts' },
    { name: 'order_addresses.view', module: 'order_addresses', description: 'View order addresses' },
    { name: 'order_addresses.create', module: 'order_addresses', description: 'Create order addresses' },
    { name: 'order_addresses.update', module: 'order_addresses', description: 'Update order addresses' },
    { name: 'order_addresses.delete', module: 'order_addresses', description: 'Delete order addresses' },
    { name: 'order_items.view', module: 'order_items', description: 'View order items' },
    { name: 'order_items.create', module: 'order_items', description: 'Create order items' },
    { name: 'order_items.update', module: 'order_items', description: 'Update order items' },
    { name: 'order_items.delete', module: 'order_items', description: 'Delete order items' },
    { name: 'order_promotions.view', module: 'order_promotions', description: 'View order promotions' },
    { name: 'order_promotions.create', module: 'order_promotions', description: 'Create order promotions' },
    { name: 'order_promotions.update', module: 'order_promotions', description: 'Update order promotions' },
    { name: 'order_promotions.delete', module: 'order_promotions', description: 'Delete order promotions' },
    { name: 'payments.view', module: 'payments', description: 'View payments' },
    { name: 'payments.create', module: 'payments', description: 'Create payments' },
    { name: 'payments.update', module: 'payments', description: 'Update payments' },
    { name: 'payments.delete', module: 'payments', description: 'Delete payments' },
    { name: 'product_reviews.view', module: 'product_reviews', description: 'View product reviews' },
    { name: 'product_reviews.create', module: 'product_reviews', description: 'Create product reviews' },
    { name: 'product_reviews.update', module: 'product_reviews', description: 'Update product reviews' },
    { name: 'product_reviews.delete', module: 'product_reviews', description: 'Delete product reviews' },
    { name: 'promotion_categories.view', module: 'promotion_categories', description: 'View promotion categories' },
    { name: 'promotion_categories.create', module: 'promotion_categories', description: 'Create promotion categories' },
    { name: 'promotion_categories.update', module: 'promotion_categories', description: 'Update promotion categories' },
    { name: 'promotion_categories.delete', module: 'promotion_categories', description: 'Delete promotion categories' },
    { name: 'promotion_items.view', module: 'promotion_items', description: 'View promotion items' },
    { name: 'promotion_items.create', module: 'promotion_items', description: 'Create promotion items' },
    { name: 'promotion_items.update', module: 'promotion_items', description: 'Update promotion items' },
    { name: 'promotion_items.delete', module: 'promotion_items', description: 'Delete promotion items' },
    { name: 'promotions.view', module: 'promotions', description: 'View promotions' },
    { name: 'promotions.create', module: 'promotions', description: 'Create promotions' },
    { name: 'promotions.update', module: 'promotions', description: 'Update promotions' },
    { name: 'promotions.delete', module: 'promotions', description: 'Delete promotions' },
    { name: 'user_roles.view', module: 'user_roles', description: 'View user roles' },
    { name: 'user_roles.create', module: 'user_roles', description: 'Create user role assignments' },
    { name: 'user_roles.update', module: 'user_roles', description: 'Update user role assignments' },
    { name: 'user_roles.delete', module: 'user_roles', description: 'Delete user role assignments' },
    { name: 'user_sessions.view', module: 'user_sessions', description: 'View user sessions' },
    { name: 'user_sessions.revoke', module: 'user_sessions', description: 'Revoke user sessions' },
    { name: 'user_sessions.cleanup', module: 'user_sessions', description: 'Clean up expired user sessions' },
    { name: 'wishlists.view', module: 'wishlists', description: 'View wishlists' },
    { name: 'wishlists.create', module: 'wishlists', description: 'Create wishlists' },
    { name: 'wishlists.delete', module: 'wishlists', description: 'Delete wishlists' }
];

const seededPermissionNames = new Set([
    'dashboard.view',
    'users.view',
    'users.create',
    'users.update',
    'users.delete',
    'roles.view',
    'roles.manage',
    'permissions.view',
    'permissions.manage',
    'products.view',
    'products.create',
    'products.update',
    'products.delete',
    'orders.view',
    'orders.create',
    'orders.update',
    'orders.cancel',
    'customers.view',
    'customers.create',
    'customers.update',
    'customers.delete',
    'reports.view',
    'admin.dashboard.view'
]);

const additionalPermissionNames = permissionCatalog
    .map((permission) => permission.name)
    .filter((permissionName) => !seededPermissionNames.has(permissionName));

const defaultRolePermissions = {
    Admin: permissionCatalog.map((permission) => permission.name),
    Manager: [
        'dashboard.view',
        'users.view',
        'users.create',
        'users.update',
        'users.delete',
        'roles.view',
        'roles.manage',
        'products.view',
        'products.create',
        'products.update',
        'products.delete',
        'orders.view',
        'orders.create',
        'orders.update',
        'orders.cancel',
        'customers.view',
        'customers.create',
        'customers.update',
        'reports.view'
    ],
    Staff: [
        'dashboard.view',
        'users.view',
        'products.view',
        'orders.view',
        'customers.view',
        'reports.view'
    ],
    Sales: [
        'dashboard.view',
        'products.view',
        'orders.view',
        'orders.create',
        'orders.update',
        'orders.cancel',
        'customers.view',
        'customers.create',
        'customers.update'
    ]
};

module.exports = {
    permissionCatalog,
    additionalPermissionNames,
    defaultRolePermissions
};
